feat: rename from CanalTP to Hove
CanalTP/libosmpbfreader pull request #11
Opened 2022-04-20 15:19 UTC by woshilapin

2022-04-20 15:23 UTC, TeXitoi requested changes

2022-04-20 15:23 UTC, TeXitoi commented on example_counter.cc
> +Copyright (c) 2001-2002, Hove
Bad date

2022-04-20 15:32 UTC, woshilapin commented on example_counter.cc
> +Copyright (c) 2001-2002, Hove
2001-2022 should be better, indeed.

2022-04-20 15:42 UTC, TeXitoi approved these changes

2022-04-21 12:45 UTC, AzHicham approved these changes

2022-04-21 12:54 UTC, merged